"""add previous_problem field

Revision ID: 8a234ee671ea
Revises: 8cf87118b999
Create Date: 2025-01-24 04:40:47.589504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a234ee671ea'
down_revision = '8cf87118b999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iterations', sa.Column('initial_prompt', sa.Text(), nullable=True))
    op.add_column('iterations', sa.Column('previous_problem', sa.Text(), nullable=True))
    op.drop_column('iterations', 'prompt_template')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iterations', sa.Column('prompt_template', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('iterations', 'previous_problem')
    op.drop_column('iterations', 'initial_prompt')
    # ### end Alembic commands ###
