"""initial migration

Revision ID: 8cf87118b999
Revises: 
Create Date: 2025-01-19 21:57:17.541963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf87118b999'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iterations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('num_qa_pairs', sa.Integer(), nullable=True),
    sa.Column('iteration_number', sa.Integer(), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('true_answer', sa.Text(), nullable=True),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('iteration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_pairs')
    op.drop_table('iterations')
    # ### end Alembic commands ###
